require 'rubygems'
require 'bundler'
Bundler.require(:default)

require_relative 'basket/catalog'
require_relative 'basket/content'
require_relative 'basket/delivery'
require_relative 'basket/delivery_charge'
require_relative 'basket/offer'
require_relative 'basket/offers'
require_relative 'basket/product'
require_relative 'basket/error'
require_relative 'basket/discounts/base'
require_relative 'basket/discounts/buy_one_get_one_free'
require_relative 'basket/discounts/buy_one_get_one_half_price'
